name: push-anon
on: 
  push:
    branches:
      - main
jobs:
  push-to-anon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - shell: bash
        env:
          KEY: ${{ secrets.ANON_KEY }}
        run: |
          rm -rf .git
          git config --global user.email "anon@anon.com"
          git config --global user.name "Anonymous"
          git init
          git remote add anon https://anon36424:$KEY@github.com/anon36424/digital_design_colab.git
          python3 .github/workflows/anonymize.py
          git add --all
          git commit -m "Initial commit"
          git branch -m master main
          git push -u anon main --force
          
      - shell: bash
        env:
          KEY: ${{ secrets.ANON_KEY }}
        run: |
          git clone https://github.com/byuccl/nb_js_diagrammers
          cd nb_js_diagrammers
          rm -rf .git
          git init
          git remote add anon https://anon36424:$KEY@github.com/anon36424/nb_js_diagrammers.git
          git add --all
          git commit -m "Initial commit"
          git branch -m master main
          git push -u anon main --force